In [12]:
import numpy as np
import os
from f_meas_gen import *
from f_observability import *

In [13]:
#Carrega Rede
Ybus_File = "ieee-30-bus.txt"
Ybus = np.loadtxt(Ybus_File, dtype='i', delimiter=',')
terminal_buses = get_terminal_bus(Ybus)

In [14]:
def count_branches(Ybus):
    n_branches = 0
    
    for line in Ybus:
        for i in line:
            n_branches += i
    n_branches = int(n_branches/2)
    return n_branches

In [15]:
class Bus_system:
    def __init__(self, Ybus):
        self.Ybus=Ybus
        self.n_bus =  np.size(Ybus,1)
        self.n_branches = count_branches(Ybus)
        self.max_meas = self.n_branches*2 + self.n_bus


In [16]:
#Parametros da Topologia
power_system = Bus_system(Ybus)

In [6]:
meas_plan =np.array( [
[1 , 1, 2, 1, 1, 1, 1],
[2 , 2, 3, 1, 1, 2, 1],
[3 , 4, 5, 1, 1, 2, 1],
[4 , 4, 6, 1, 1, 3, 1],
[5 , 5, 4, 1, 1, 3, 1],
[6 , 1, 1, 1, 2, 1, 1],
[7 , 3, 3, 1, 2, 3, 1],
[8 , 5, 5, 1, 2, 5, 1],
[9 , 6, 6, 1, 2, 6, 1],
])

In [5]:
meas_plan =np.array( [
[1 , 1, 3, 1, 1, 1, 1],
[2 , 2, 1, 1, 1, 2, 1],
[3 , 2, 3, 1, 1, 2, 1],
[4 , 3, 1, 1, 1, 3, 1],
[5 , 3, 2, 1, 1, 3, 1],
[6 , 4, 3, 1, 1, 4, 1],
[7 , 4, 5, 1, 1, 4, 1],
[8 , 4, 6, 1, 1, 4, 1],
[9 , 5, 1, 1, 1, 5, 1],
[10, 5, 4, 1, 1, 5, 1],
[11, 1, 1, 1, 2, 1, 1],
[12, 2, 2, 1, 2, 2, 1],
[13, 4, 4, 1, 2, 4, 1],
[14, 5, 5, 1, 2, 5, 1],
])

In [17]:
#Plano de medição 30 barras com PMU Abel
meas_plan =np.array( [   [1 ,  3, 3, 1, 3,  3, 1 ],
                         [2 , 28,28, 1, 3, 28, 1 ],
                         [3 , 1 ,3 , 1 ,1 ,1 , 1 ],
                         [4 , 2 ,4 , 1 ,1 ,2 , 1 ],
                         [5 , 2 ,5 , 1 ,1 ,2 , 1 ],
                         [6 , 4 ,6 , 1 ,1 ,4 , 1 ],
                         [7 , 5 ,7 , 1 ,1 ,5 , 1 ],
                         [8 , 6 ,7 , 1 ,1 ,6 , 1 ],
                         [9 , 6 ,9 , 1 ,1 ,6 , 1 ],
                         [10, 6 ,10, 1 ,1 ,6 , 1 ],
                         [11, 9 ,11, 1 ,1 ,9 , 1 ],
                         [12, 12,13, 1, 1, 12, 1 ],
                         [13, 12,14, 1, 1, 12, 1 ],
                         [14, 12,16, 1, 1, 12, 1 ],
                         [15, 14,15, 1, 1, 14, 1 ],
                         [16, 15,18, 1, 1, 15, 1 ],
                         [17, 15,23, 1, 1, 15, 1 ],
                         [18, 16,17, 1, 1, 16, 1 ],
                         [19, 18,19, 1, 1, 18, 1 ],
                         [20, 19,20, 1, 1, 19, 1 ],
                         [21, 21,10, 1, 1, 21, 1 ],
                         [22, 22,10, 1, 1, 22, 1 ],
                         [23, 24,23, 1, 1, 24, 1 ],
                         [24, 25,26, 1, 1, 25, 1 ],
                         [25, 25,27, 1, 1, 25, 1 ],
                         [26, 29,27, 1, 1, 29, 1 ],
                         [27, 29,30, 1, 1, 29, 1 ],
                         [28,  1, 1, 1, 2,  1, 1 ],
                         [29,  2, 2, 1, 2,  2, 1 ],
                         [30,  4, 4, 1, 2,  4, 1 ],
                         [31,  5, 5, 1, 2,  5, 1 ],
                         [32,  9, 9, 1, 2,  9, 1 ],
                         [33, 10,10, 1, 2, 10, 1 ],
                         [34, 12,12, 1, 2, 12, 1 ],
                         [35, 18,18, 1, 2, 18, 1 ],
                         [36, 19,19, 1, 2, 19, 1 ],
                         [37, 21,21, 1, 2, 21, 1 ],
                         [38, 22,22, 1, 2, 22, 1 ],
                         [39, 24,24, 1, 2, 24, 1 ],
                         [40, 27,27, 1, 2, 27, 1 ],
                         [41, 28,27, 1, 7, 28, 1 ],
                         [42, 28, 8, 1, 7, 28, 1 ],
                         [43, 28, 6, 1, 7, 28, 1 ]
                          ])

In [10]:
meas_plan =np.array([     [   1,  1   ,2    ,1  ,1  ,1   ,1],
                          [   2,  1   ,3    ,1  ,1  ,1   ,1],
                          [   3,  4   ,5    ,1  ,1  ,4   ,1],
                          [   4,  3   ,5    ,1  ,1  ,3   ,1],
                          [   5,  5   ,6    ,1  ,1  ,5   ,1],
                          [   6,  6   ,7    ,1  ,1  ,6   ,1],
                          [   7,  8   ,9    ,1  ,1  ,8   ,1],
                          [   8,  8   ,5    ,1  ,1  ,8   ,1],
                          [   9,  9   ,10   ,1  ,1  ,9   ,1],
                          [  10,  4   ,11   ,1  ,1  ,4   ,1],
                          [  11,  5   ,11   ,1  ,1  ,5   ,1],
                          [  12,  11  ,12   ,1  ,1  ,11  ,1],
                          [  13,  2   ,12   ,1  ,1  ,2   ,1],
                          [  14,  3   ,12   ,1  ,1  ,3   ,1],
                          [  15,  7   ,12   ,1  ,1  ,7   ,1],
                          [  16,  11  ,13   ,1  ,1  ,11  ,1],
                          [  17,  12  ,14   ,1  ,1  ,12  ,1],
                          [  18,  13  ,15   ,1  ,1  ,13  ,1],
                          [  19,  14  ,15   ,1  ,1  ,14  ,1],
                          [  20,  12  ,16   ,1  ,1  ,12  ,1],
                          [  21,  15  ,17   ,1  ,1  ,15  ,1],
                          [  22,  16  ,17   ,1  ,1  ,16  ,1],
                          [  23,  17  ,18   ,1  ,1  ,17  ,1],
                          [  24,  18  ,19   ,1  ,1  ,18  ,1],
                          [  25,  19  ,20   ,1  ,1  ,19  ,1],
                          [  26,  15  ,19   ,1  ,1  ,15  ,1],
                          [  27,  20  ,21   ,1  ,1  ,20  ,1],
                          [  28,  21  ,22   ,1  ,1  ,21  ,1],
                          [  29,  22  ,23   ,1  ,1  ,22  ,1],
                          [  30,  23  ,24   ,1  ,1  ,23  ,1],
                          [  31,  23  ,25   ,1  ,1  ,23  ,1],
                          [  32,  26  ,25   ,1  ,1  ,26  ,1],
                          [  33,  25  ,27   ,1  ,1  ,25  ,1],
                          [  34,  27  ,28   ,1  ,1  ,27  ,1],
                          [  35,  28  ,29   ,1  ,1  ,28  ,1],
                          [  36,  30  ,17   ,1  ,1  ,30  ,1],
                          [  37,  8   ,30   ,1  ,1  ,8   ,1],
                          [  38,  26  ,30   ,1  ,1  ,26  ,1],
                          [  39,  17  ,31   ,1  ,1  ,17  ,1],
                          [  40,  29  ,31   ,1  ,1  ,29  ,1],
                          [  41,  23  ,32   ,1  ,1  ,23  ,1],
                          [  42,  31  ,32   ,1  ,1  ,31  ,1],
                          [  43,  27  ,32   ,1  ,1  ,27  ,1],
                          [  44,  15  ,33   ,1  ,1  ,15  ,1],
                          [  45,  19  ,34   ,1  ,1  ,19  ,1],
                          [  46,  35  ,36   ,1  ,1  ,35  ,1],
                          [  47,  35  ,37   ,1  ,1  ,35  ,1],
                          [  48,  33  ,37   ,1  ,1  ,33  ,1],
                          [  49,  34  ,36   ,1  ,1  ,34  ,1],
                          [  50,  34  ,37   ,1  ,1  ,34  ,1],
                          [  51,  38  ,37   ,1  ,1  ,38  ,1],
                          [  52,  37  ,39   ,1  ,1  ,37  ,1],
                          [  53,  37  ,40   ,1  ,1  ,37  ,1],
                          [  54,  30  ,38   ,1  ,1  ,30  ,1],
                          [  55,  39  ,40   ,1  ,1  ,39  ,1],
                          [  56,  40  ,41   ,1  ,1  ,40  ,1],
                          [  57,  40  ,42   ,1  ,1  ,40  ,1],
                          [  58,  41  ,42   ,1  ,1  ,41  ,1],
                          [  59,  43  ,44   ,1  ,1  ,43  ,1],
                          [  60,  34  ,43   ,1  ,1  ,34  ,1],
                          [  61,  44  ,45   ,1  ,1  ,44  ,1],
                          [  62,  45  ,46   ,1  ,1  ,45  ,1],
                          [  63,  46  ,47   ,1  ,1  ,46  ,1],
                          [  64,  46  ,48   ,1  ,1  ,46  ,1],
                          [  65,  47  ,49   ,1  ,1  ,47  ,1],
                          [  66,  42  ,49   ,1  ,1  ,42  ,1],
                          [  67,  45  ,49   ,1  ,1  ,45  ,1],
                          [  68,  48  ,49   ,1  ,1  ,48  ,1],
                          [  69,  49  ,50   ,1  ,1  ,49  ,1],
                          [  70,  49  ,51   ,1  ,1  ,49  ,1],
                          [  71,  51  ,52   ,1  ,1  ,51  ,1],
                          [  72,  52  ,53   ,1  ,1  ,52  ,1],
                          [  73,  53  ,54   ,1  ,1  ,53  ,1],
                          [  74,  49  ,54   ,1  ,1  ,49  ,1],
                          [  75,  54  ,55   ,1  ,1  ,54  ,1],
                          [  76,  54  ,56   ,1  ,1  ,54  ,1],
                          [  77,  55  ,56   ,1  ,1  ,55  ,1],
                          [  78,  56  ,57   ,1  ,1  ,56  ,1],
                          [  79,  50  ,57   ,1  ,1  ,50  ,1],
                          [  80,  56  ,58   ,1  ,1  ,56  ,1],
                          [  81,  51  ,58   ,1  ,1  ,51  ,1],
                          [  82,  54  ,59   ,1  ,1  ,54  ,1],
                          [  83,  56  ,59   ,1  ,1  ,56  ,1],
                          [  84,  55  ,59   ,1  ,1  ,55  ,1],
                          [  85,  59  ,60   ,1  ,1  ,59  ,1],
                          [  86,  59  ,61   ,1  ,1  ,59  ,1],
                          [  87,  60  ,61   ,1  ,1  ,60  ,1],
                          [  88,  60  ,62   ,1  ,1  ,60  ,1],
                          [  89,  61  ,62   ,1  ,1  ,61  ,1],
                          [  90,  63  ,59   ,1  ,1  ,63  ,1],
                          [  91,  63  ,64   ,1  ,1  ,63  ,1],
                          [  92,  64  ,61   ,1  ,1  ,64  ,1],
                          [  93,  38  ,65   ,1  ,1  ,38  ,1],
                          [  94,  64  ,65   ,1  ,1  ,64  ,1],
                          [  95,  49  ,66   ,1  ,1  ,49  ,1],
                          [  96,  62  ,66   ,1  ,1  ,62  ,1],
                          [  97,  62  ,67   ,1  ,1  ,62  ,1],
                          [  98,  65  ,66   ,1  ,1  ,65  ,1],
                          [  99,  66  ,67   ,1  ,1  ,66  ,1],
                          [ 100,  65  ,68   ,1  ,1  ,65  ,1],
                          [ 101,  47  ,69   ,1  ,1  ,47  ,1],
                          [ 102,  49  ,69   ,1  ,1  ,49  ,1],
                          [ 103,  68  ,69   ,1  ,1  ,68  ,1],
                          [ 104,  69  ,70   ,1  ,1  ,69  ,1],
                          [ 105,  24  ,70   ,1  ,1  ,24  ,1],
                          [ 106,  70  ,71   ,1  ,1  ,70  ,1],
                          [ 107,  24  ,72   ,1  ,1  ,24  ,1],
                          [ 108,  71  ,72   ,1  ,1  ,71  ,1],
                          [ 109,  71  ,73   ,1  ,1  ,71  ,1],
                          [ 110,  70  ,74   ,1  ,1  ,70  ,1],
                          [ 111,  70  ,75   ,1  ,1  ,70  ,1],
                          [ 112,  69  ,75   ,1  ,1  ,69  ,1],
                          [ 113,  74  ,75   ,1  ,1  ,74  ,1],
                          [ 114,  76  ,77   ,1  ,1  ,76  ,1],
                          [ 115,  69  ,77   ,1  ,1  ,69  ,1],
                          [ 116,  75  ,77   ,1  ,1  ,75  ,1],
                          [ 117,  77  ,78   ,1  ,1  ,77  ,1],
                          [ 118,  78  ,79   ,1  ,1  ,78  ,1],
                          [ 119,  77  ,80   ,1  ,1  ,77  ,1],
                          [ 120,  79  ,80   ,1  ,1  ,79  ,1],
                          [ 121,  68  ,81   ,1  ,1  ,68  ,1],
                          [ 122,  81  ,80   ,1  ,1  ,81  ,1],
                          [ 123,  77  ,82   ,1  ,1  ,77  ,1],
                          [ 124,  82  ,83   ,1  ,1  ,82  ,1],
                          [ 125,  83  ,84   ,1  ,1  ,83  ,1],
                          [ 126,  83  ,85   ,1  ,1  ,83  ,1],
                          [ 127,  84  ,85   ,1  ,1  ,84  ,1],
                          [ 128,  85  ,86   ,1  ,1  ,85  ,1],
                          [ 129,  86  ,87   ,1  ,1  ,86  ,1],
                          [ 130,  85  ,88   ,1  ,1  ,85  ,1],
                          [ 131,  85  ,89   ,1  ,1  ,85  ,1],
                          [ 132,  88  ,89   ,1  ,1  ,88  ,1],
                          [ 133,  89  ,90   ,1  ,1  ,89  ,1],
                          [ 134,  90  ,91   ,1  ,1  ,90  ,1],
                          [ 135,  89  ,92   ,1  ,1  ,89  ,1],
                          [ 136,  91  ,92   ,1  ,1  ,91  ,1],
                          [ 137,  92  ,93   ,1  ,1  ,92  ,1],
                          [ 138,  92  ,94   ,1  ,1  ,92  ,1],
                          [ 139,  93  ,94   ,1  ,1  ,93  ,1],
                          [ 140,  94  ,95   ,1  ,1  ,94  ,1],
                          [ 141,  80  ,96   ,1  ,1  ,80  ,1],
                          [ 142,  82  ,96   ,1  ,1  ,82  ,1],
                          [ 143,  94  ,96   ,1  ,1  ,94  ,1],
                          [ 144,  80  ,97   ,1  ,1  ,80  ,1],
                          [ 145,  80  ,98   ,1  ,1  ,80  ,1],
                          [ 146,  80  ,99   ,1  ,1  ,80  ,1],
                          [ 147,  92  ,100  ,1  ,1  ,92  ,1],
                          [ 148,  94  ,100  ,1  ,1  ,94  ,1],
                          [ 149,  95  ,96   ,1  ,1  ,95  ,1],
                          [ 150,  96  ,97   ,1  ,1  ,96  ,1],
                          [ 151,  98  ,100  ,1  ,1  ,98  ,1],
                          [ 152,  99  ,100  ,1  ,1  ,99  ,1],
                          [ 153,  100 ,101  ,1  ,1  ,100 ,1],
                          [ 154,  92  ,102  ,1  ,1  ,92  ,1],
                          [ 155,  101 ,102  ,1  ,1  ,101 ,1],
                          [ 156,  100 ,103  ,1  ,1  ,100 ,1],
                          [ 157,  100 ,104  ,1  ,1  ,100 ,1],
                          [ 158,  103 ,104  ,1  ,1  ,103 ,1],
                          [ 159,  100 ,106  ,1  ,1  ,100 ,1],
                          [ 160,  105 ,107  ,1  ,1  ,105 ,1],
                          [ 161,  105 ,108  ,1  ,1  ,105 ,1],
                          [ 162,  106 ,107  ,1  ,1  ,106 ,1],
                          [ 163,  108 ,109  ,1  ,1  ,108 ,1],
                          [ 164,  103 ,110  ,1  ,1  ,103 ,1],
                          [ 165,  109 ,110  ,1  ,1  ,109 ,1],
                          [ 166,  110 ,111  ,1  ,1  ,110 ,1],
                          [ 167,  110 ,112  ,1  ,1  ,110 ,1],
                          [ 168,  17  ,113  ,1  ,1  ,17  ,1],
                          [ 169,  32  ,113  ,1  ,1  ,32  ,1],
                          [ 170,  32  ,114  ,1  ,1  ,32  ,1],
                          [ 171,  27  ,115  ,1  ,1  ,27  ,1],
                          [ 172,  114 ,115  ,1  ,1  ,114 ,1],
                          [ 173,  68  ,116  ,1  ,1  ,68  ,1],
                          [ 174,  12  ,117  ,1  ,1  ,12  ,1],
                          [ 175,  75  ,118  ,1  ,1  ,75  ,1],
                          [ 176,  76  ,118  ,1  ,1  ,76  ,1]])

In [8]:

meas_plan =np.array([
                    [  1    ,1	 ,2	    ,1,1,  1,1],
                    [  2    ,1	 ,3	    ,1,1,  2,1],
                    [  3    ,4	 ,5	    ,1,1,  3,1],
                    [  4    ,3	 ,5	    ,1,1,  4,1],
                    [  5    ,5	 ,6	    ,1,1,  5,1],
                    [  6    ,6	 ,7	    ,1,1,  6,1],
                    [  7    ,8	 ,9	    ,1,1,  7,1],
                    [  8    ,8	 ,5	    ,1,1,  8,1],
                    [  9    ,9	 ,10	,1,1,  9,1],
                    [ 10    ,4	 ,11	,1,1, 10,1],
                    [ 11    ,5	 ,11	,1,1, 11,1],
                    [ 12    ,11	 ,12	,1,1, 12,1],
                    [ 13    ,2	 ,12	,1,1, 13,1],
                    [ 14    ,3	 ,12	,1,1, 14,1],
                    [ 15    ,7	 ,12	,1,1, 15,1],
                    [ 16    ,11	 ,13	,1,1, 16,1],
                    [ 17    ,12	 ,14	,1,1, 17,1],
                    [ 18    ,13	 ,15	,1,1, 18,1],
                    [ 19    ,14	 ,15	,1,1, 19,1],
                    [ 20    ,12	 ,16	,1,1, 20,1],
                    [ 21    ,15	 ,17	,1,1, 21,1],
                    [ 22    ,16	 ,17	,1,1, 22,1],
                    [ 23    ,17	 ,18	,1,1, 23,1],
                    [ 24    ,18	 ,19	,1,1, 24,1],
                    [ 25    ,19	 ,20	,1,1, 25,1],
                    [ 26    ,15	 ,19	,1,1, 26,1],
                    [ 27    ,20	 ,21	,1,1, 27,1],
                    [ 28    ,21	 ,22	,1,1, 28,1],
                    [ 29    ,22	 ,23	,1,1, 29,1],
                    [ 30    ,23	 ,24	,1,1, 30,1],
                    [ 31    ,23	 ,25	,1,1, 31,1],
                    [ 32    ,26	 ,25	,1,1, 32,1],
                    [ 33    ,25	 ,27	,1,1, 33,1],
                    [ 34    ,27	 ,28	,1,1, 34,1],
                    [ 35    ,28	 ,29	,1,1, 35,1],
                    [ 36    ,30	 ,17	,1,1, 36,1],
                    [ 37    ,8	 ,30	,1,1, 37,1],
                    [ 38    ,26	 ,30	,1,1, 38,1],
                    [ 39    ,17	 ,31	,1,1, 39,1],
                    [ 40    ,29	 ,31	,1,1, 40,1],
                    [ 41    ,23	 ,32	,1,1, 41,1],
                    [ 42    ,31	 ,32	,1,1, 42,1],
                    [ 43    ,27	 ,32	,1,1, 43,1],
                    [ 44    ,15	 ,33	,1,1, 44,1],
                    [ 45    ,19	 ,34	,1,1, 45,1],
                    [ 46    ,35	 ,36	,1,1, 46,1],
                    [ 47    ,35	 ,37	,1,1, 47,1],
                    [ 48    ,33	 ,37	,1,1, 48,1],
                    [ 49    ,34	 ,36	,1,1, 49,1],
                    [ 50    ,34	 ,37	,1,1, 50,1],
                    [ 51    ,38	 ,37	,1,1, 51,1],
                    [ 52    ,37	 ,39	,1,1, 52,1],
                    [ 53    ,37	 ,40	,1,1, 53,1],
                    [ 54    ,30	 ,38	,1,1, 54,1],
                    [ 55    ,39	 ,40	,1,1, 55,1],
                    [ 56    ,40	 ,41	,1,1, 56,1],
                    [ 57    ,40	 ,42	,1,1, 57,1],
                    [ 58    ,41	 ,42	,1,1, 58,1],
                    [ 59    ,43	 ,44	,1,1, 59,1],
                    [ 60    ,34	 ,43	,1,1, 60,1],
                    [ 61    ,44	 ,45	,1,1, 61,1],
                    [ 62    ,45	 ,46	,1,1, 62,1],
                    [ 63    ,46	 ,47	,1,1, 63,1],
                    [ 64    ,46	 ,48	,1,1, 64,1],
                    [ 65    ,47	 ,49	,1,1, 65,1],
                    [ 66    ,42	 ,49	,1,1, 66,1],
                    [ 67    ,45	 ,49	,1,1, 67,1],
                    [ 68    ,48	 ,49	,1,1, 68,1],
                    [ 69    ,49	 ,50	,1,1, 69,1],
                    [ 70    ,49	 ,51	,1,1, 70,1],
                    [ 71    ,51	 ,52	,1,1, 71,1],
                    [ 72    ,52	 ,53	,1,1, 72,1],
                    [ 73    ,53	 ,54	,1,1, 73,1],
                    [ 74    ,49	 ,54	,1,1, 74,1],
                    [ 75    ,54	 ,55	,1,1, 75,1],
                    [ 76    ,54	 ,56	,1,1, 76,1],
                    [ 77    ,55	 ,56	,1,1, 77,1],
                    [ 78    ,56	 ,57	,1,1, 78,1],
                    [ 79    ,50	 ,57	,1,1, 79,1],
                    [ 80    ,56	 ,58	,1,1, 80,1],
                    [ 81    ,51	 ,58	,1,1, 81,1],
                    [ 82    ,54	 ,59	,1,1, 82,1],
                    [ 83    ,56	 ,59	,1,1, 83,1],
                    [ 84    ,55	 ,59	,1,1, 84,1],
                    [ 85    ,59	 ,60	,1,1, 85,1],
                    [ 86    ,59	 ,61	,1,1, 86,1],
                    [ 87    ,60	 ,61	,1,1, 87,1],
                    [ 88    ,60	 ,62	,1,1, 88,1],
                    [ 89    ,61	 ,62	,1,1, 89,1],
                    [ 90    ,63	 ,59	,1,1, 90,1],
                    [ 91    ,63	 ,64	,1,1, 91,1],
                    [ 92    ,64	 ,61	,1,1, 92,1],
                    [ 93    ,38	 ,65	,1,1, 93,1],
                    [ 94    ,64	 ,65	,1,1, 94,1],
                    [ 95    ,49	 ,66	,1,1, 95,1],
                    [ 96    ,62	 ,66	,1,1, 96,1],
                    [ 97    ,62	 ,67	,1,1, 97,1],
                    [ 98    ,65	 ,66	,1,1, 98,1],
                    [ 99    ,66	 ,67	,1,1, 99,1],
                    [100	,65	 ,68	,1,1,100,1],
                    [101	,47	 ,69	,1,1,101,1],
                    [102	,49	 ,69	,1,1,102,1],
                    [103	,68	 ,69	,1,1,103,1],
                    [104	,69	 ,70	,1,1,104,1],
                    [105	,24	 ,70	,1,1,105,1],
                    [106	,70	 ,71	,1,1,106,1],
                    [107	,24	 ,72	,1,1,107,1],
                    [108	,71	 ,72	,1,1,108,1],
                    [109	,71	 ,73	,1,1,109,1],
                    [110	,70	 ,74	,1,1,110,1],
                    [111	,70	 ,75	,1,1,111,1],
                    [112	,69	 ,75	,1,1,112,1],
                    [113	,74	 ,75	,1,1,113,1],
                    [114	,76	 ,77	,1,1,114,1],
                    [115	,69	 ,77	,1,1,115,1],
                    [116	,75	 ,77	,1,1,116,1],
                    [117	,77	 ,78	,1,1,117,1],
                    [118	,78	 ,79	,1,1,118,1],
                    [119	,77	 ,80	,1,1,119,1],
                    [120	,79	 ,80	,1,1,120,1],
                    [121	,68	 ,81	,1,1,121,1],
                    [122	,81	 ,80	,1,1,122,1],
                    [123	,77	 ,82	,1,1,123,1],
                    [124	,82	 ,83	,1,1,124,1],
                    [125	,83	 ,84	,1,1,125,1],
                    [126	,83	 ,85	,1,1,126,1],
                    [127	,84	 ,85	,1,1,127,1],
                    [128	,85	 ,86	,1,1,128,1],
                    [129	,86	 ,87	,1,1,129,1],
                    [130	,85	 ,88	,1,1,130,1],
                    [131	,85	 ,89	,1,1,131,1],
                    [132	,88	 ,89	,1,1,132,1],
                    [133	,89	 ,90	,1,1,133,1],
                    [134	,90	 ,91	,1,1,134,1],
                    [135	,89	 ,92	,1,1,135,1],
                    [136	,91	 ,92	,1,1,136,1],
                    [137	,92	 ,93	,1,1,137,1],
                    [138	,92	 ,94	,1,1,138,1],
                    [139	,93	 ,94	,1,1,139,1],
                    [140	,94	 ,95	,1,1,140,1],
                    [141	,80	 ,96	,1,1,141,1],
                    [142	,82	 ,96	,1,1,142,1],
                    [143	,94	 ,96	,1,1,143,1],
                    [144	,80	 ,97	,1,1,144,1],
                    [145	,80	 ,98	,1,1,145,1],
                    [146	,80	 ,99	,1,1,146,1],
                    [147	,92	 ,100	,1,1,147,1],
                    [148	,94	 ,100	,1,1,148,1],
                    [149	,95	 ,96	,1,1,149,1],
                    [150	,96	 ,97	,1,1,150,1],
                    [151	,98	 ,100	,1,1,151,1],
                    [152	,99	 ,100	,1,1,152,1],
                    [153	,100 ,101	,1,1,153,1],
                    [154	,92	 ,102	,1,1,154,1],
                    [155	,101 ,102	,1,1,155,1],
                    [156	,100 ,103	,1,1,156,1],
                    [157	,100 ,104	,1,1,157,1],
                    [158	,103 ,104	,1,1,158,1],
                    [159	,100 ,106	,1,1,159,1],
                    [160	,105 ,107	,1,1,160,1],
                    [161	,105 ,108	,1,1,161,1],
                    [162	,106 ,107	,1,1,162,1],
                    [163	,108 ,109	,1,1,163,1],
                    [164	,103 ,110	,1,1,164,1],
                    [165	,109 ,110	,1,1,165,1],
                    [166	,110 ,111	,1,1,166,1],
                    [167	,110 ,112	,1,1,167,1],
                    [168	,17	 ,113	,1,1,168,1],
                    [169	,32	 ,113	,1,1,169,1],
                    [170	,32	 ,114	,1,1,170,1],
                    [171	,27	 ,115	,1,1,171,1],
                    [172	,114 ,115	,1,1,172,1],
                    [173	,68	 ,116	,1,1,173,1],
                    [174	,12	 ,117	,1,1,174,1],
                    [175	,75	 ,118	,1,1,175,1],
                    [176	,76	 ,118	,1,1,176,1]
])


In [7]:
H= build_jacobian_matrix(power_system.Ybus,meas_plan)
G= build_gain_matrix(H)
E=build_covariance_matrix(G,H)
H.shape

(9, 5)

In [18]:
def save_case_for_GPU_CA(Bus_system,measurement_plan):
    Ybus = Bus_system.Ybus
    n_bus = Bus_system.n_bus
    n_measurements = len(measurement_plan)

    set_of_UMs = set()
    for meas in meas_plan:
        set_of_UMs.add(meas[1])
    n_UMs = len(set_of_UMs)
    UMs = np.array(list(set_of_UMs))

    filename = 'Caso' + str(n_bus) +'b'+str(n_measurements)+'m.txt'

    H = build_jacobian_matrix(Ybus,measurement_plan)
    G = build_gain_matrix(H)
    E = build_covariance_matrix(G,H)

    print(H)

    file = open(filename,'w')
    np.savetxt(file, [n_UMs],delimiter=' ',  fmt ='%i')
    np.savetxt(file, [n_measurements],delimiter=' ',  fmt ='%i')
    np.savetxt(file, UMs.reshape(1, UMs.shape[0]),delimiter=' ',  fmt ='%i')
    np.savetxt(file,measurement_plan, delimiter=' ',fmt = '%i')
    np.savetxt(file,E, delimiter=' ')
    file.close()

In [19]:
save_case_for_GPU_CA(power_system,meas_plan)

[[ 0.  0.  1. ...  0.  0.  0.]
 [ 0.  0.  0. ...  1.  0.  0.]
 [ 1.  0. -1. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  1.  0.  0.]
 [ 0.  0.  0. ...  1.  0.  0.]
 [ 0.  0.  0. ...  1.  0.  0.]]


: 